# Generated by Django 4.0.4 on 2022-04-24 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('td', models.FileField(upload_to='')),
                ('tp', models.FileField(upload_to='')),
                ('cour', models.FileField(upload_to='')),
                ('projet', models.FileField(upload_to='')),
                ('quizz', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('coeffcient', models.IntegerField()),
                ('credit', models.IntegerField()),
                ('contenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.contenu')),
            ],
        ),
    ]
