# Generated by Django 4.0.4 on 2022-04-25 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_cour_projet_quizz_td_tp_remove_modules_contenu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cour',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.modules'),
        ),
        migrations.AddField(
            model_name='projet',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.modules'),
        ),
        migrations.AddField(
            model_name='quizz',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.modules'),
        ),
        migrations.AddField(
            model_name='td',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.modules'),
        ),
        migrations.AddField(
            model_name='tp',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.modules'),
        ),
    ]
