# Generated by Django 4.0.4 on 2022-04-25 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_cour_module_projet_module_quizz_module_td_module_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Modules',
            new_name='Module',
        ),
    ]
