# Generated by Django 4.0.4 on 2022-04-26 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_speciality_speciality_alter_speciality_year_and_more'),
        ('content', '0004_rename_modules_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='prof',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.professor'),
        ),
    ]
