# Generated by Django 4.0.4 on 2022-04-26 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_speciality_speciality_alter_speciality_year_and_more'),
        ('content', '0005_module_prof'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='prof',
        ),
        migrations.AddField(
            model_name='module',
            name='prof',
            field=models.ManyToManyField(to='accounts.professor'),
        ),
    ]
