# Generated by Django 4.0.4 on 2022-04-26 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_remove_module_prof_module_prof'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='prof',
        ),
    ]
