# Generated by Django 4.0.4 on 2022-04-26 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_professor_modules'),
        ('content', '0007_remove_module_prof'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='Speciality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.speciality'),
        ),
    ]
