# Generated by Django 4.0.4 on 2022-04-26 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_rename_quizz_homework'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PROJET',
        ),
    ]
