# Generated by Django 4.0.4 on 2022-04-27 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_professor_modules'),
        ('content', '0012_alter_module_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='prof',
            field=models.ManyToManyField(to='accounts.professor'),
        ),
    ]
