# Generated by Django 4.0.4 on 2022-05-22 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_speciality_speciality'),
        ('content', '0016_alter_correction_correction_alter_cour_cour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='Speciality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.speciality'),
        ),
        migrations.DeleteModel(
            name='homework',
        ),
    ]
