# Generated by Django 4.0.4 on 2022-04-25 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Years',
            new_name='Year',
        ),
    ]
