# Generated by Django 4.0.4 on 2022-04-25 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_years_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='year',
            old_name='Year',
            new_name='year',
        ),
        migrations.AlterField(
            model_name='speciality',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.year', unique=True),
        ),
    ]
