# Generated by Django 4.0.4 on 2022-04-25 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_year_year_year_alter_speciality_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciality',
            name='year',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.year'),
        ),
    ]
