# Generated by Django 4.0.4 on 2022-04-25 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_speciality_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciality',
            name='speciality',
            field=models.CharField(choices=[('MI', 'MI'), ('INFO', 'INFO'), ('MATH', 'MATH'), ('SI', 'SI'), ('ISIL', 'ISIL'), ('MATH', 'MATH'), ('STW', 'STW'), ('GLSD', 'GLSD'), ('MATHAPPLQ', 'MATHAPPLQ'), ('STW', 'STW'), ('GLSD', 'GLSD'), ('MATHAPPLQ', 'MATHAPPLQ')], default='MI', max_length=10),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.year'),
        ),
        migrations.AlterField(
            model_name='year',
            name='year',
            field=models.CharField(choices=[('L1', 'L1'), ('L2', 'L2'), ('L3', 'L3'), ('M1', 'M1'), ('M2', 'M2')], default='L1', max_length=2),
        ),
    ]
