# Generated by Django 4.0.4 on 2022-04-26 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_remove_module_prof'),
        ('accounts', '0005_alter_speciality_speciality_alter_speciality_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='modules',
            field=models.ManyToManyField(to='content.module'),
        ),
    ]
