# Generated by Django 4.0.4 on 2022-04-27 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_professor_modules'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='modules',
        ),
    ]
