# Generated by Django 4.0.4 on 2022-04-27 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_professor_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='nickname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
