# Generated by Django 4.0.4 on 2022-04-27 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_remove_module_prof'),
        ('accounts', '0008_professor_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='nickname',
        ),
        migrations.AddField(
            model_name='professor',
            name='modules',
            field=models.ManyToManyField(to='content.module'),
        ),
    ]
