# Generated by Django 4.0.4 on 2022-05-06 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_professor_nickname_professor_modules'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speciality',
            name='year',
        ),
        migrations.AlterField(
            model_name='speciality',
            name='speciality',
            field=models.CharField(choices=[('MI - L1', 'MI - L1'), ('INFO - L2', 'INFO - L2'), ('MATH - L2', 'MATH - L2'), ('SI - L3', 'SI - L3'), ('ISIL - L3', 'ISIL - L3'), ('MATH - L3', 'MATH - L3'), ('STW - M1', 'STW - M1'), ('GLSD - M1', 'GLSD - M1'), ('MATHAPPLQ - M1', 'MATHAPPLQ - M1'), ('STW - M2', 'STW - M2'), ('GLSD - M2', 'GLSD - M2'), ('MATHAPPLQ - M2', 'MATHAPPLQ - M2')], default='MI', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(default='M', max_length=1, null=True),
        ),
        migrations.DeleteModel(
            name='Year',
        ),
    ]
