# Generated by Django 4.0.4 on 2022-05-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_speciality_speciality'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciality',
            name='schedule',
            field=models.FileField(null=True, upload_to='Schedules'),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='speciality',
            field=models.CharField(default='MI', max_length=20, unique=True),
        ),
    ]
